from constants import *
def add_user() :
    user_n = input(names)
    n  = global_info.get("name")
    n.append(user_n)
    global_info.update(name = n)
    user_a = int(input(ages))
    a = global_info.get("age")
    a.append(user_a)
    global_info.update(age = a)
    user_s=input(sexes)
    s = global_info.get("sex")
    s.append(user_s)
    global_info.update(sex = s)
    print(global_info)
    return user_n
def del_it() :
    ind = input(del_user)
    l = global_info.get("name")
    u_index = l.index(ind)
    l.pop(u_index)
    global_info.update(name = l)
    u = global_info.get("age")
    u.pop(u_index)
    global_info.update(age = u)
    f = global_info.get("sex")
    f.pop(u_index)
    global_info.update(sex = f)
    print(global_info)
def return_user () :
    user = input(ret_user)
    user_get = global_info.get("name")
    age_get = global_info.get("age")
    sex_get = global_info.get("sex")
    name_index = user_get.index(user)
    print(user_get[name_index] , age_get[name_index , "лет"] , sex_get[name_index])